### ISSUE TITLE
Create list jobs on home

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bitvagas/bitvagas.github.io#6]

**Comment by rands0n** [comment]
How page jobs is listed? Like posts lists?

**Comment by Anderson-Juhasc** [comment]
Yeah, like this:

![jobs](https://cloud.githubusercontent.com/assets/423705/5850065/8ad9f6f6-a1d5-11e4-938d-20e1b7a36af8.png)

**Comment by Anderson-Juhasc** [comment]
Disregarded.
